# Project Configuration — Dev, Acceptance, Production

dev:
  catalog: dev
  schema: supercharge_ai
  volume: data
  llm_endpoint: databricks-llama-4-maverick
  embedding_endpoint: databricks-gte-large-en
  warehouse_id: ""
  vector_search_endpoint: supercharge_vs_endpoint
  genie_space_id: ""

acc:
  catalog: acc
  schema: supercharge_ai
  volume: data
  llm_endpoint: databricks-llama-4-maverick
  embedding_endpoint: databricks-gte-large-en
  warehouse_id: ""
  vector_search_endpoint: supercharge_vs_endpoint
  genie_space_id: ""

prd:
  catalog: prd
  schema: supercharge_ai
  volume: data
  llm_endpoint: databricks-llama-4-maverick
  embedding_endpoint: databricks-gte-large-en
  warehouse_id: ""
  vector_search_endpoint: supercharge_vs_endpoint
  genie_space_id: ""
